/**
 * Generates a timestamp in the format YYYYMMDDHHMMSS.
 * This is required for M-Pesa API requests.
 */
export const getTimestamp = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');
  const seconds = String(now.getSeconds()).padStart(2, '0');
  return `${year}${month}${day}${hours}${minutes}${seconds}`;
};

/**
 * Generates the password for M-Pesa STK Push requests.
 * It's a base64 encoding of Shortcode + Passkey + Timestamp.
 * @param shortcode - The M-Pesa business shortcode.
 * @param passkey - The M-Pesa passkey.
 * @param timestamp - The timestamp generated by getTimestamp().
 */
export const generatePassword = (shortcode: string, passkey: string, timestamp: string): string => {
  const buffer = Buffer.from(`${shortcode}${passkey}${timestamp}`);
  return buffer.toString('base64');
};